name: Bug report
description: Report a reproducible problem with Jarvis
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug! Please search existing issues first.
  - type: input
    id: version
    attributes:
      label: App version
      description: Find it in the app title bar or the latest release tag (e.g., 0.3.0)
      placeholder: 0.3.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows 11 (x64)
        - Windows 10 (x64)
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal steps. Include screenshots if helpful.
      placeholder: |
        1. Open app
        2. Click mic
        3. Say "Jarvis"
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copy any relevant logs or errors.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues
          required: true

