name: Feature request
description: Suggest an improvement or new capability
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! We accept feature requests via issues.
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to achieve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should Jarvis behave?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I searched existing issues
          required: true

